%YAML:1.0

Global_file_directory: "/home/qjs/cloudGlobal.pcd"   #全局地图文件位置
local_cloud_frame:  "/velodyne_cloud_registered"     #局部雷达原始帧话题 (/laser_cloud_map)
global_z: "0"       #这两个参数是调整栅格地图的Z轴直通滤波的范围
local_z: "0.27"


